AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for deploying a Hugging Face model on SageMaker.

Resources:
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn: !Ref SageMakerExecutionRole
      PrimaryContainer:
        Image: 763104351884.dkr.ecr.eu-central-1.amazonaws.com/jumpstart-dft-hf-llm-mistral-7b-ins-20240109-1-20240109-1138560
        Mode: SingleModel
        Environment:
          HF_MODEL_ID: 'jumpstart-dft-hf-llm-mistral-7b-ins-20240109-084901'  # replace with your Hugging Face model name
          HF_TASK: 'text-classification'  # replace with your task
          SAGEMAKER_PROGRAM: inference.py
          SAGEMAKER_SUBMIT_DIRECTORY: /opt/ml/model/code
          SAGEMAKER_CONTAINER_LOG_LEVEL: '20'
          SAGEMAKER_REGION: 'eu-central-1'

  SageMakerEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - VariantName: AllTraffic
          ModelName: !Ref SageMakerModel
          InitialInstanceCount: 1
          InstanceType: ml.m5.large

  SageMakerEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !Ref SageMakerEndpointConfig

Parameters:
  SageMakerExecutionRole:
    Type: String
    Default: arn:aws:iam::019915518575:role/service-role/AmazonSageMaker-ExecutionRole-20231212T174551
    Description: The AWS IAM role for SageMaker execution.

Outputs:
  SageMakerEndpointName:
    Description: The name of the SageMaker endpoint.
    Value: !Ref SageMakerEndpoint
